spring:
  application:
    name: GBC
app:
  app-name: ${spring.application.name}
  # 使用${变量名}引用pom文件中变量
  description: @project.description@
  # 使用@@引用pom.xml文件中定义的变量
  version: @project.version@
  # 使用${变量名}引用pom文件中变量
  build-time: @timestamp@
  # stop-watch-log
  stop-watch-log-enabled: true
  logback:
    #    app-name: logback-ds
    #    app-version: 3.0
    is-prod-env: true
    prod:
      file-path: ../data/logs/prod
      file-name: ${spring.application.name}prod
      ext:
        watch-path: com.male
        log-level: info
    test:
      file-path: ../data/logs/test
      file-name: ${spring.application.name}test
      ext:
        watch-path: com.male
        log-level: debug

# tomcat 参数调优配置
server:
  tomcat:
    # springboot 同时可以处理多少请求 100+8192
    # 最大等待数
    accept-count: 100
    # 最大链接数 1024的倍数
    max-connections: 10240
    threads:
      # 最大线程数 1核2G默认配置200，4核8G默认配置800
      max: 800
      # 最小线程数
      min-spare: 10